### ISSUE TITLE
Implement differentiating with respect to x^2

### ISSUE THREAD

**Issue by certik** [symengine/symengine#145]
As reported by @thilinarmtb.

Probably this might not be important at this moment but I found that I can't do something like below. 

```
In [34]: var("t")
Out[34]: t

In [35]: f = function_symbol("f", t**2)
In [37]: f.diff(t**2)
TypeError: Argument 'x' has incorrect type (expected csympy.lib.csympy_wrapper.Symbol, got csympy.lib.csympy_wrapper.Pow)
```

This is due to the fact that currently `Derivative::diff` only takes `Symbols` as arguments. Is this the intended behaviour? I checked with `SymPy` and If I am not mistaken `SymPy` doesn't do this kind of differentiation either. 

```
>>>diff(sin(x), x**2)
Traceback (most recent call last): File "<string>", line 1, in <module> File "/base/data/home/apps/s~sympy-live-hrd/43.373169527249054993/sympy/sympy/core/function.py", line 1526, in diff return Derivative(f, *symbols, **kwargs) File "/base/data/home/apps/s~sympy-live-hrd/43.373169527249054993/sympy/sympy/core/function.py", line 925, in __new__ Can\'t differentiate wrt the variable: %s, %s''' % (v, count))) ValueError: Can't differentiate wrt the variable: x**2, 1
```

Wolfram-alpha doesn't execute this kind of derivatives but represent it in Leibniz notation. See [here](https://www.wolframalpha.com/input/?i=diff%28sinx%2C+x**2%29). Would it be okay at this moment to do something like below ? 

```
In [1]: var("t")
Out[1]: t

In [2]: f = function_symbol("f", t**2)
In [3]: f.diff(t**2)
Out[3]: Derivative(f(t^2), t^2)
```

Here `f` doesn't necessarily need to be a function of `t**2`, it can be a function of `t` or a function of a function of `t`. Is there a reason to avoid this kind of derivatives?

**Comment by abhinavagarwal07** [comment]
for f and g be function of t, such that g'(t)≠0
by chain rule
df(t)/dg(t) = ( df(t)/dt ) * ( ( dg(t)/dt)^(-1) )
for g = t, it essentially becomes df(t)/dt
for g=t**2 it becomes df(t)/dt * (1/2t)
