### ISSUE TITLE
Matrices need an xreplace() method.

### ISSUE THREAD

**Issue by moorepants** [symengine/symengine#1456]
Getting this error when running sympy mechanics with symengine:

```
___________ sympy/physics/mechanics/tests/test_kane.py:test_one_dof ____________
Traceback (most recent call last):
  File "sympy/utilities/runtests.py", line 1277, in _timeout
    function()
  File "/home/travis/build/sympy/sympy/sympy/physics/mechanics/tests/test_kane.py", line 40, in test_one_dof
    KM.mass_matrix_full.LUsolve(KM.forcing_full)) == zeros(2, 1)
  File "sympy/physics/mechanics/kane.py", line 641, in forcing_full
    return -Matrix([f1.xreplace(self.kindiffdict()), self._f_d.xreplace(self.kindiffdict()), self._f_dnh.xreplace(self.kindiffdict())])
AttributeError: 'symengine.lib.symengine_wrapper.MutableDenseMatrix' object has no attribute 'xreplace'
```

**Comment by isuruf** [comment]
This issue was moved to symengine/symengine.py#245
