### ISSUE TITLE
Lambdify with LLVM does not work with Piecewise

### ISSUE THREAD

**Issue by stephweissm** [symengine/symengine#1485]
I might have misunderstood something, but wasn't this implemented in symengine/symengine#1446?
```
$ conda install -c symengine/label/dev python-symengine
$ python
>>> from symengine import Symbol, Lambdify
>>> from symengine.lib.symengine_wrapper import Piecewise
>>> x = Symbol('x')
>>> p = Piecewise((-x, x<0), (x*x*x, True))
>>> p
Piecewise((-x, x < 0), (x**3, True))
>>> f = Lambdify([x], [p])
>>> f = Lambdify([x], [p], backend='llvm')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "symengine_wrapper.pyx", line 4782, in symengine.lib.symengine_wrapper.Lambdify
  File "symengine_wrapper.pyx", line 4481, in symengine.lib.symengine_wrapper._Lambdify.__init__
  File "symengine_wrapper.pyx", line 4701, in symengine.lib.symengine_wrapper.LLVMDouble._init
RuntimeError: Not implemented.
```

**Comment by isuruf** [comment]
It wasn't. I can review or help with a PR if you'd like to implement it.
