### ISSUE TITLE
Crash while paring invalid string

### ISSUE THREAD

**Issue by SoilRos** [symengine/symengine#2002]
## Description

While trying to parse the string `cos(t) > 0.95 ? 1 : 0`, which is obviously wrong for symengine syntax, I got the following address sanitizer report (without sanitizer it simply crashes).

## Log
```
==23529==ERROR: AddressSanitizer: BUS on unknown address (pc 0x0001959f2b38 bp 0x00016f0afcf0 sp 0x00016f0afce0 T0)
==23529==The signal is caused by a READ memory access.
==23529==Hint: this fault was caused by a dereference of a high value address (see register values below).  Disassemble the provided pc to learn which register was used.
    #0 0x1959f2b38 in _Unwind_GetIP+0xe0 (libunwind.dylib:arm64e+0x9b38)
    #1 0x18918af3c in __gxx_personality_v0+0x124 (libc++abi.dylib:arm64e+0x13f3c)
    #2 0x137d5076c in unwind_phase2+0x180 (libunwind.1.0.dylib:arm64+0x876c)
    #3 0x137d509a4 in _Unwind_Resume+0x60 (libunwind.1.0.dylib:arm64+0x89a4)
    #4 0x1387b4584 in SymEngine::Tokenizer::lex(yy::parser::value_type*)+0x4c0 (libsymengine.0.11.2.dylib:arm64+0x124584)
    #5 0x1387ac2fc in yy::parser::parse()+0xf0 (libsymengine.0.11.2.dylib:arm64+0x11c2fc)
    #6 0x1387ae34c in SymEngine::Parser::parse(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool)+0x84 (libsymengine.0.11.2.dylib:arm64+0x11e34c)
   ...
```

## Expected behavior

On parsing error, I would expect an exception (e.g., `SymEngine::ParseError`) being thrown together with a string explaining the issue (e.g., token `?` is invalid).

## Environment

* **Hardware**: Apple M3 Max
* **Operating System**: macOS 14.1 (23B2073)
* **Compiler**: Apple clang
  * **Version**: 15.0.0 (clang-1500.1.0.2.5)
  * **Target**: arm64-apple-darwin23.1.0
  * **Thread model**: posix
* **SymEngine Version**: 0.11.2

**Comment by rikardn** [comment]
I tested this using the latest symengine.py and actually got a proper error:

```python
import symengine

symengine.sympify("cos(t) > 0.95 ? 1 : 0")
```

```
Traceback (most recent call last):

  File "/tmp/ipykernel_8401/2068866104.py", line 1, in <module>
    symengine.sympify("cos(t) > 0.95 ? 1 : 0")

  File "symengine_wrapper.pyx", line 523, in symengine.lib.symengine_wrapper.sympify

RuntimeError: Unknown token: '?'
```
