### ISSUE TITLE
`test_lambda_double` crashes on LLVM assertions

### ISSUE THREAD

**Issue by mgorny** [symengine/symengine#2076]
When LLVM is built with assertions enabled, the following test crashes:

```
46/59 Testing: test_lambda_double
46/59 Test: test_lambda_double
Command: "/tmp/symengine/build/symengine/tests/eval/test_lambda_double"
Directory: /tmp/symengine/build/symengine/tests/eval
"test_lambda_double" start time: Dec 31 08:36 CET
Output:
----------------------------------------------------------
test_lambda_double: /var/tmp/portage/llvm-core/llvm-19.1.6/work/llvm/lib/Passes/PassBuilderPipelines.cpp:547: llvm::FunctionPassManager llvm::PassBuilder::buildFunctionSimplificationPipeline(llvm::OptimizationLevel, llvm::ThinOrFullLTOPhase): Assertion `Level != OptimizationLevel::O0 && "Must request optimizations!"' failed.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test_lambda_double is a Catch v2.13.8 host application.
Run with -? for options

-------------------------------------------------------------------------------
Check llvm and lambda are equal
-------------------------------------------------------------------------------
/tmp/symengine/symengine/tests/eval/test_lambda_double.cpp:290
...............................................................................

/tmp/symengine/symengine/tests/eval/test_lambda_double.cpp:290: FAILED:
  {Unknown expression after the reported line}
due to a fatal error condition:
  SIGABRT - Abort (abnormal termination) signal

===============================================================================
test cases:   6 |   5 passed | 1 failed
assertions: 144 | 143 passed | 1 failed

<end of output>
Test time =   0.30 sec
```

Reproduced with bf1051bebe2dd0bde06c9166170eca32edc912ae, and LLVM 19.1.6.

Looks like it's invalid to use `PB.buildFunctionSimplificationPipeline()` with an opt level of 0.

**Comment by mgorny** [comment]
If I fix that via:

```diff
diff --git a/symengine/llvm_double.cpp b/symengine/llvm_double.cpp
index 793d0878..44390052 100644
--- a/symengine/llvm_double.cpp
+++ b/symengine/llvm_double.cpp
@@ -252,16 +252,19 @@ void LLVMVisitor::init(const vec_basic &inputs, const vec_basic &outputs,
     } else if (opt_level == 2) {
         pb_opt_level = OptimizationLevel::O2;
     }
+
+    if (opt_level != 0) {
 #if (LLVM_VERSION_MAJOR < 6)
-    FPM = PB.buildFunctionSimplificationPipeline(pb_opt_level);
+      FPM = PB.buildFunctionSimplificationPipeline(pb_opt_level);
 #elif (LLVM_VERSION_MAJOR < 12)
-    FPM = PB.buildFunctionSimplificationPipeline(
-        pb_opt_level, llvm::PassBuilder::ThinLTOPhase::None);
+      FPM = PB.buildFunctionSimplificationPipeline(
+          pb_opt_level, llvm::PassBuilder::ThinLTOPhase::None);
 #else
-    FPM = PB.buildFunctionSimplificationPipeline(
-        pb_opt_level, llvm::ThinOrFullLTOPhase::None);
+      FPM = PB.buildFunctionSimplificationPipeline(
+          pb_opt_level, llvm::ThinOrFullLTOPhase::None);
 #endif
-    FPM.run(*F, FAM);
+      FPM.run(*F, FAM);
+    }
 
     // std::cout << "Optimized LLVM IR" << std::endl;
     // module->print(llvm::errs(), nullptr);
```

I get another assertion failure:

```
46/59 Testing: test_lambda_double
46/59 Test: test_lambda_double
Command: "/tmp/symengine/build/symengine/tests/eval/test_lambda_double"
Directory: /tmp/symengine/build/symengine/tests/eval
"test_lambda_double" start time: Dec 31 08:46 CET
Output:
----------------------------------------------------------
Initializing 2297us
Saving 0us
test_lambda_double: /var/tmp/portage/llvm-core/llvm-19.1.6/work/llvm/lib/ExecutionEngine/ExecutionEngine.cpp:189: std::string llvm::ExecutionEngine::getMangledName(const llvm::GlobalValue*): Assertion `GV->hasName() && "Global must have name."' failed.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test_lambda_double is a Catch v2.13.8 host application.
Run with -? for options

-------------------------------------------------------------------------------
Check llvm save and load
-------------------------------------------------------------------------------
/tmp/symengine/symengine/tests/eval/test_lambda_double.cpp:415
...............................................................................

/tmp/symengine/symengine/tests/eval/test_lambda_double.cpp:415: FAILED:
due to a fatal error condition:
  SIGABRT - Abort (abnormal termination) signal

===============================================================================
test cases:   8 |   7 passed | 1 failed
assertions: 250 | 249 passed | 1 failed

<end of output>
Test time =   0.49 sec
```

**Comment by isuruf** [comment]
Is it possible to get a stack trace?

**Comment by mgorny** [comment]
Getting there :-).

**Comment by mgorny** [comment]
```
#0  0x00007fffed095ccc in ?? () from /usr/lib64/libc.so.6
#1  0x00007fffed03ec26 in raise () from /usr/lib64/libc.so.6
#2  0x00007fffed0268fa in abort () from /usr/lib64/libc.so.6
#3  0x00007fffed02681e in ?? () from /usr/lib64/libc.so.6
#4  0x00007fffed036f96 in __assert_fail () from /usr/lib64/libc.so.6
#5  0x00007ffff1336ab9 in llvm::ExecutionEngine::getMangledName[abi:cxx11](llvm::GlobalValue const*) ()
   from /usr/lib/llvm/19/lib64/libLLVM.so.19.1
#6  0x00007ffff133714f in llvm::ExecutionEngine::updateGlobalMapping(llvm::GlobalValue const*, void*) ()
   from /usr/lib/llvm/19/lib64/libLLVM.so.19.1
#7  0x00007ffff14240b2 in llvm::MCJIT::getPointerToFunction(llvm::Function*) () from /usr/lib/llvm/19/lib64/libLLVM.so.19.1
#8  0x0000555555e67dea in SymEngine::LLVMVisitor::loads (this=0x7fffffffc2d0, 
    s="\177ELF\002\001\001\000\000\000\000\000\000\000\000\000\001\000>\000\001", '\000' <repeats 19 times>, "X\003\000\000\000\000\000\000\000\000\000\000@\000\000\000\000\000@\000\n\000\001\000\216\201\370\306\323R\032@\000\000\000\000\000\000\000\000\363\017\036\372AVSH\203\3548H\211\363I\211\376\362\017\020\a\362\017\021D$\030\362\017\020O\b\362\017\021\f$H\215|$0H\215t$(H\270\000\000\000\000\000\000\000\000\377\320\362\017\020D$(\362\017\020L$0\362\017\021L$ f\017(\321\362\017Y\321\362\017\021T$\020\362\017X\312f\017(\321\362\017\020\f$\362\017Y\311\362\017Y\311\362A\017YN\020\362\017"...) at /tmp/symengine/symengine/llvm_double.cpp:1007
#9  0x0000555555b169f0 in C_A_T_C_H_T_E_S_T_14 () at /tmp/symengine/symengine/tests/eval/test_lambda_double.cpp:450
#10 0x0000555555ef7f82 in Catch::TestInvokerAsFunction::invoke (this=0x5555562562a0)
    at /tmp/symengine/symengine/utilities/catch/catch.hpp:14328
#11 0x0000555555ef70fb in Catch::TestCase::invoke (this=0x555556275078) at /tmp/symengine/symengine/utilities/catch/catch.hpp:14167
#12 0x0000555555ef0f0c in Catch::RunContext::invokeActiveTestCase (this=0x7fffffffca80)
    at /tmp/symengine/symengine/utilities/catch/catch.hpp:13027
#13 0x0000555555ef0c1d in Catch::RunContext::runCurrentTest (this=0x7fffffffca80, redirectedCout="", redirectedCerr="")
    at /tmp/symengine/symengine/utilities/catch/catch.hpp:13000
#14 0x0000555555eef646 in Catch::RunContext::runTest (this=0x7fffffffca80, testCase=...)
    at /tmp/symengine/symengine/utilities/catch/catch.hpp:12761
#15 0x0000555555ef29a1 in Catch::(anonymous namespace)::TestGroup::execute (this=0x7fffffffca70)
    at /tmp/symengine/symengine/utilities/catch/catch.hpp:13354
#16 0x0000555555ef3eee in Catch::Session::runInternal (this=0x7fffffffcd70)
    at /tmp/symengine/symengine/utilities/catch/catch.hpp:13560
#17 0x0000555555ef3be0 in Catch::Session::run (this=0x7fffffffcd70) at /tmp/symengine/symengine/utilities/catch/catch.hpp:13516
#18 0x0000555555f367d1 in Catch::Session::run<char> (this=0x7fffffffcd70, argc=1, argv=0x7fffffffd038)
    at /tmp/symengine/symengine/utilities/catch/catch.hpp:13238
#19 0x0000555555f0c3e1 in main (argc=1, argv=0x7fffffffd038) at /tmp/symengine/symengine/utilities/catch/catch.cpp:25
```

**Comment by mgorny** [comment]
And I don't think it's going to be easy. A dumb approach of setting a random function name leads to another error:

```
LLVM ERROR: Program used external function 'dummy' which could not be resolved!
```
