### ISSUE TITLE
Call 'make install' from setup.py

### ISSUE THREAD

**Issue by certik** [symengine/symengine#395]
Currently the `setup.py` calls `cmake` and `make`, but not `make install`, instead it uses distutils to figure out which files to install. The problem with that approach is that now we need to test `setup.py install` as well as `make install`, otherwise bugs like #390 can slip into our build system.

See also https://github.com/PyCMake/PyCMake/issues/10.

**Comment by certik** [comment]
I tried the following patch:
```diff
diff --git a/setup.py b/setup.py
index fa5e9c4..abd4a71 100644
--- a/setup.py
+++ b/setup.py
@@ -41,6 +41,10 @@ def cmake_build():
     if subprocess.call("make") != 0:
         raise EnvironmentError("error calling make")
 
+def make_install():
+    if subprocess.call(["make", "instal"]) != 0:
+        raise EnvironmentError("error calling make")
+
 class BuildWithCmake(_build):
     _build_opts = _build.user_options
     user_options = [
@@ -95,8 +99,7 @@ class InstallWithCmake(_install):
             cmake_opts.extend(self.define)
 
     def run(self):
-        # can't use super() here because _install is an old style class in 2.7
-        _install.run(self)
+        make_install()
 
 long_description = '''
 CSymPy is a standalone fast C++ symbolic manipulation library.
```
But it fails with:
```
$ CC=gcc CXX=g++ python setup.py install --prefix=xx --define="COMMON_DIR:PATH=$HASHSTACK"
running install
make: *** No rule to make target `instal'.  Stop.
Traceback (most recent call last):
  File "setup.py", line 121, in <module>
    'install' : InstallWithCmake,
  File "/home/certik/repos/hashstack/default/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/certik/repos/hashstack/default/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/certik/repos/hashstack/default/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 102, in run
    make_install()
  File "setup.py", line 46, in make_install
    raise EnvironmentError("error calling make")
EnvironmentError: error calling make
```
So it looks like distutils are calling the `InstallWithCmake` immediately.

**Comment by pbrady** [comment]
Just a quick clarification: we use setuptools by default rather than distutils since subclassing the distutils build and install functions doesn't work when installing via pip (which uses setuptools).  It's a minor point but if we start relying on distutils it could cause problems when installing via pip (#284).

Also I think you need to change:
`if subprocess.call(["make", "instal"]) != 0:` to
`if subprocess.call(["make", "install"]) != 0:`

**Comment by certik** [comment]
I fixed the missing `l`, still the same error.

The `InstallWithCmake.run()` is run first, which calls `BuildWithCmake.run`, which install things into a `build/lib` directory, then `InstallWithCmake.run()` resumes and copies stuff from the `build/lib` directory into `xx/lib/python2.7/site-packages/`, and also compiles `.py` into `.pyc`.

**Comment by certik** [comment]
One way to do that is as follows:
```diff
diff --git a/setup.py b/setup.py
index fa5e9c4..9192e7c 100644
--- a/setup.py
+++ b/setup.py
@@ -27,7 +27,11 @@ if not use_setuptools:
     from distutils.core import setup
     from distutils.command.install import install as _install
 
-cmake_opts = [("WITH_PYTHON","yes")]
+cmake_opts = [
+        ("WITH_PYTHON","yes"),
+        ("CMAKE_INSTALL_PREFIX", "xx"),
+        ("PYTHON_INSTALL_PATH", "lib/python2.7/site-packages"),
+        ]
 
 def process_opts(opts):
     return ['-D'+'='.join(o) for o in opts]
@@ -38,7 +42,10 @@ def cmake_build():
     if subprocess.call(cmake_cmd) != 0:
         raise EnvironmentError("error calling cmake")
 
-    if subprocess.call("make") != 0:
+    if subprocess.call(["make", "-j16"]) != 0:
+        raise EnvironmentError("error calling make")
+
+    if subprocess.call(["make", "install"]) != 0:
         raise EnvironmentError("error calling make")
 
 class BuildWithCmake(_build):
@@ -111,8 +118,6 @@ setup(name = "csympy",
       author_email = "",
       license = "MIT",
       url = "https://github.com/sympy/csympy",
-      packages = ["csympy", "csympy.lib", "csympy.tests"],
-      package_data= {'' : ['lib/csympy_wrapper.so']},
       cmdclass={
           'build' : BuildWithCmake,
           'install' : InstallWithCmake,
```
TODO:
* [ ] Change `"xx"` to the installation directory, taken from distutils/setuptools
* [ ] Get the string `"lib/python2.7/site-packages"` from distutils/setuptools
* [ ] Remove the `-j16` or perhaps allow the user to set it

One problem is that now distutils don't know about what files are installed, e.g.:
```
certik@redhawk:~/repos/csympy/xx/lib/python2.7/site-packages(master)$ cat csympy-git-py2.7.egg-info/SOURCES.txt 
setup.py
csympy.egg-info/PKG-INFO
csympy.egg-info/SOURCES.txt
csympy.egg-info/dependency_links.txt
csympy.egg-info/top_level.txt
```
But I think that's fine. CMake actually creates a file (after `make install` is run):
```
certik@redhawk:~/repos/csympy(travis_python_tests)$ cat install_manifest.txt 
/home/certik/repos/csympy/xx/lib/libcsympy.a
/home/certik/repos/csympy/xx/include/add.h
/home/certik/repos/csympy/xx/include/csympy_assert.h
/home/certik/repos/csympy/xx/include/functions.h
/home/certik/repos/csympy/xx/include/monomials.h
/home/certik/repos/csympy/xx/include/number.h
/home/certik/repos/csympy/xx/include/rings.h
/home/certik/repos/csympy/xx/include/basic.h
/home/certik/repos/csympy/xx/include/csympy_rcp.h
/home/certik/repos/csympy/xx/include/integer.h
/home/certik/repos/csympy/xx/include/mul.h
/home/certik/repos/csympy/xx/include/pow.h
/home/certik/repos/csympy/xx/include/constants.h
/home/certik/repos/csympy/xx/include/symbol.h
/home/certik/repos/csympy/xx/include/basic-inl.h
/home/certik/repos/csympy/xx/include/dict.h
/home/certik/repos/csympy/xx/include/matrix.h
/home/certik/repos/csympy/xx/include/ntheory.h
/home/certik/repos/csympy/xx/include/rational.h
/home/certik/repos/csympy/xx/include/complex.h
/home/certik/repos/csympy/xx/include/visitor.h
/home/certik/repos/csympy/xx/include/eval_double.h
/home/certik/repos/csympy/xx/include/diophantine.h
/home/certik/repos/csympy/xx/include/cwrapper.h
/home/certik/repos/csympy/xx/include/csympy_config.h
/home/certik/repos/csympy/xx/lib/libteuchos.a
/home/certik/repos/csympy/xx/lib/python2.7/site-packages/csympy/__init__.py
/home/certik/repos/csympy/xx/lib/python2.7/site-packages/csympy/utilities.py
/home/certik/repos/csympy/xx/lib/python2.7/site-packages/csympy/compatibility.py
/home/certik/repos/csympy/xx/lib/python2.7/site-packages/csympy/lib/csympy_wrapper.so
/home/certik/repos/csympy/xx/lib/python2.7/site-packages/csympy/lib/__init__.py
```
So we can parse it and give it to setuptools ---- but we don't want setuptools to install things twice, and I don't know if setuptools needs to know what is installed, besides the `SOURCES.txt` file.

**Comment by isuruf** [comment]
Fixed in symengine/symengine.py#8
