### ISSUE TITLE
EnvironmentError: error calling cmake

### ISSUE THREAD

**Issue by mkarakoc** [symengine/symengine#670]
Sorry, but I could not find any place to ask help about the following error. 
```
sudo python setup.py install
---------------------------------
running install
running build
CMake Error at CMakeLists.txt:5 (find_package):
  Could not find a package configuration file provided by "SymEngine"
  (requested version 0.1.0) with any of the following names:

    SymEngineConfig.cmake
    symengine-config.cmake

  Add the installation prefix of "SymEngine" to CMAKE_PREFIX_PATH or set
  "SymEngine_DIR" to a directory containing one of the above files.  If
  "SymEngine" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/home/cahitarf/Desktop/symengine/symengine.py/CMakeFiles/CMakeOutput.log".
CMake Error: Unable to open check cache file for write. /home/cahitarf/Desktop/symengine/symengine.py/CMakeFiles/cmake.check_cache
Traceback (most recent call last):
  File "setup.py", line 190, in <module>
    'install' : InstallWithCmake,
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 171, in run
    _install.run(self)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 71, in run
    _install.run(self)
  File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
    self.run_command('build')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 110, in run
    self.cmake_build()
  File "setup.py", line 87, in cmake_build
    raise EnvironmentError("error calling cmake")
EnvironmentError: error calling cmake
```

**Comment by certik** [comment]
This issue probably belongs into the https://github.com/symengine/symengine.py repository. It looks like the `symengine.py` cmake didn't find the `symengine` C++ library. Try to install it with:
```
python setup.py install build --symengine-dir=/path/to/symengine/install/dir 
```
and specify the path to your symengine C++ installation. Let me know if it works or if you have any questions.

**Comment by mkarakoc** [comment]
This still gives same error.
```bash
python setup.py install build --symengine-dir=../symengine/symengine/
```

Is the following showing the install dir? Otherwise, where is the install dir?
```
../symengine/symengine$ ls
add.cpp              constants.h          eval_mpfr.h      ntheory.h        rings.h
add.h                CTestTestfile.cmake  expression.h     number.cpp       series.cpp
basic.cpp            cwrapper.cpp         functions.cpp    number.h         series.h
basic.h              cwrapper.h           functions.h      polynomial.cpp   sparse_matrix.cpp
basic-inl.h          dense_matrix.cpp     integer.cpp      polynomial.h     symbol.cpp
catch                dict.cpp             integer.h        pow.cpp          symbol.h
CMakeFiles           dict.h               lambda_double.h  pow.h            symengine_assert.h
cmake_install.cmake  diophantine.cpp      libsymengine.a   printer.cpp      symengine_config.h
CMakeLists.txt       diophantine.h        Makefile         printer.h        symengine_config.h.in
complex.cpp          eval_arb.cpp         matrix.cpp       rational.cpp     symengine_rcp.cpp
complex_double.cpp   eval_arb.h           matrix.h         rational.h       symengine_rcp.h
complex_double.h     eval_double.cpp      monomials.cpp    real_double.cpp  tests
complex.h            eval_double.h        monomials.h      real_double.h    teuchos
complex_mpc.cpp      eval_mpc.cpp         mul.cpp          real_mpfr.cpp    type_codes.inc
complex_mpc.h        eval_mpc.h           mul.h            real_mpfr.h      visitor.cpp
constants.cpp        eval_mpfr.cpp        ntheory.cpp      rings.cpp        visitor.h
```

**Comment by certik** [comment]
Perfect!
